machine:
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker build -t bluk/docker-consul-template-haproxy .

test:
  override:
    - docker run -d bluk/docker-consul-template-haproxy; sleep 10

deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push bluk/docker-consul-template-haproxy
